  pre_build:
    commands:
      - echo Logging in to Docker Hub...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t mittey/kek123 .
      - docker tag mittey/kek123 mittey/kek123 .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...