version: 2
jobs:
   build:
     docker:
       - image: circleci/node:carbon
     steps:
       - checkout

       - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

       - run:
          name: Build and push Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t mittey/sample-express:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push mittey/sample-express:$TAG