version: 2
jobs:
   build:
     docker:
       - image: circleci/node:carbon
     steps:
       - checkout
       - run: echo "hello world"
       - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS 